
## configure travis to use the right compiler
dist: trusty
sudo: false	# do not need sudo support
<<<<<<< HEAD
os: Linux
=======
>>>>>>> performance


language: cpp
#compiler: gcc

# Cacnhing dependencies
<<<<<<< HEAD
cache: ccache
 directories:
  - openmpi	# build mpi only need to done onece
=======
cache:
 directories:
  - openmpi-4.0.2	# build mpi only need to done onece
>>>>>>> performance


# MPI project
before_install:
 - sh ./get_openmpi.sh 

# savelisting branches (specifies the branch to build)	
branches:
 only:
<<<<<<< HEAD
  - master
  - travis
=======
 - master
 - load_balancing 
>>>>>>> performance


script:
 - mkdir build
 - mkdir outputs
 - mkdir tests
 - export PATH=$PATH:~/openmpi-4.0.2/bin/
 - cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc
 - cd build
<<<<<<< HEAD



# - cmake .. 	# configuring cmake in the current build folder
=======
 - cmake .. 	# configuring cmake in the current build folder
>>>>>>> performance
# - cmake --build . -- -j2  #parallel build (two virtual CPU available)
